version: '3.2'
services:
  mysql:
    build: 
      context: .
      dockerfile: Dockerfile.mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    ports: 
      - "3307:3306"

  app:
    build:
      context: .
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/cdss_decoupling
      - SPRING_DATASOURCE_USERNAME=answer
      - SPRING_DATASOURCE_PASSWORD=answer99q
    ports: 
      - "8083:8083"
    restart: on-failure:5