FROM mysql:5
ENV MYSQL_DATABASE cdss_decoupling
ENV MYSQL_ROOT_PASSWORD password
COPY ./src/main/resources/SQL/create_database.sql /docker-entrypoint-initdb.d/
COPY ./src/main/resources/SQL/create_tables.sql /docker-entrypoint-initdb.d/
COPY ./src/main/resources/SQL/populate_data.sql /docker-entrypoint-initdb.d/
EXPOSE 3306