version: '3.2'
services:
  mysql:
    build: 
      context: .
      dockerfile: Dockerfile.mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    ports: 
      - "3306:3306"

  app:
    image:
      registry.gitlab.com/ems-test-harness/cdss-ems:latest
    environment: 
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/cdss_decoupling
    ports: 
      - "8083"
    restart: on-failure:5