FROM mysql:5.6
ENV MYSQL_DATABASE cdss_decoupling
ENV MYSQL_ROOT_PASSWORD password
COPY src/main/resources/sql/create_database.sql /docker-entrypoint-initdb.d/
COPY src/main/resources/sql/create_tables.sql /docker-entrypoint-initdb.d/
COPY src/main/resources/sql/populate_data.sql /docker-entrypoint-initdb.d/
EXPOSE 3306