//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.15 at 03:22:47 PM GMT 
//


package uk.nhs.ctp.service.report.org.hl7.v3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * A character string that may have a type-tag signifying its role in the address. Typical parts that exist in about every address are street, house number, or post box, postal code, city, country but other roles may be defined regionally, nationally, or on an enterprise level (e.g. in military addresses). Addresses are usually broken up into lines, which are indicated by special line-breaking delimiter elements (e.g., DEL).
 * 
 * <p>Java class for ADXP complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ADXP">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:hl7-org:v3}ST">
 *       &lt;attribute name="partType" type="{urn:hl7-org:v3}cs_AddressPartType" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ADXP")
@XmlSeeAlso({
   uk.nhs.ctp.service.report.org.hl7.v3.AD.Delimiter.class,
   uk.nhs.ctp.service.report.org.hl7.v3.AD.Country.class,
   uk.nhs.ctp.service.report.org.hl7.v3.AD.State.class,
   uk.nhs.ctp.service.report.org.hl7.v3.AD.County.class,
   uk.nhs.ctp.service.report.org.hl7.v3.AD.City.class,
   uk.nhs.ctp.service.report.org.hl7.v3.AD.PostalCode.class,
   uk.nhs.ctp.service.report.org.hl7.v3.AD.Precinct.class,
   uk.nhs.ctp.service.report.org.hl7.v3.AD.StreetAddressLine.class,
   uk.nhs.ctp.service.report.org.hl7.v3.AD.HouseNumber.class,
   uk.nhs.ctp.service.report.org.hl7.v3.AD.HouseNumberNumeric.class,
   uk.nhs.ctp.service.report.org.hl7.v3.AD.Direction.class,
   uk.nhs.ctp.service.report.org.hl7.v3.AD.StreetName.class,
   uk.nhs.ctp.service.report.org.hl7.v3.AD.StreetNameBase.class,
   uk.nhs.ctp.service.report.org.hl7.v3.AD.StreetNameType.class,
   uk.nhs.ctp.service.report.org.hl7.v3.AD.AdditionalLocator.class,
   uk.nhs.ctp.service.report.org.hl7.v3.AD.UnitID.class,
   uk.nhs.ctp.service.report.org.hl7.v3.AD.UnitType.class,
   uk.nhs.ctp.service.report.org.hl7.v3.AD.Carrier.class,
   uk.nhs.ctp.service.report.org.hl7.v3.AD.CensusTract.class,
   uk.nhs.ctp.service.report.org.hl7.v3.ADNPfITCodedCountry.Delimiter.class,
   uk.nhs.ctp.service.report.org.hl7.v3.ADNPfITCodedCountry.State.class,
   uk.nhs.ctp.service.report.org.hl7.v3.ADNPfITCodedCountry.County.class,
   uk.nhs.ctp.service.report.org.hl7.v3.ADNPfITCodedCountry.City.class,
   uk.nhs.ctp.service.report.org.hl7.v3.ADNPfITCodedCountry.PostalCode.class,
   uk.nhs.ctp.service.report.org.hl7.v3.ADNPfITCodedCountry.StreetAddressLine.class,
   uk.nhs.ctp.service.report.org.hl7.v3.ADNPfITCodedCountry.HouseNumber.class,
   uk.nhs.ctp.service.report.org.hl7.v3.ADNPfITCodedCountry.HouseNumberNumeric.class,
   uk.nhs.ctp.service.report.org.hl7.v3.ADNPfITCodedCountry.Direction.class,
   uk.nhs.ctp.service.report.org.hl7.v3.ADNPfITCodedCountry.StreetName.class,
   uk.nhs.ctp.service.report.org.hl7.v3.ADNPfITCodedCountry.StreetNameBase.class,
   uk.nhs.ctp.service.report.org.hl7.v3.ADNPfITCodedCountry.StreetNameType.class,
   uk.nhs.ctp.service.report.org.hl7.v3.ADNPfITCodedCountry.AdditionalLocator.class,
   uk.nhs.ctp.service.report.org.hl7.v3.ADNPfITCodedCountry.UnitID.class,
   uk.nhs.ctp.service.report.org.hl7.v3.ADNPfITCodedCountry.UnitType.class,
   uk.nhs.ctp.service.report.org.hl7.v3.ADNPfITCodedCountry.Carrier.class,
   uk.nhs.ctp.service.report.org.hl7.v3.ADNPfITCodedCountry.CensusTract.class
})
public class ADXP
    extends ST
{

    @XmlAttribute(name = "partType")
    protected CsAddressPartType partType;

    /**
     * Gets the value of the partType property.
     * 
     * @return
     *     possible object is
     *     {@link CsAddressPartType }
     *     
     */
    public CsAddressPartType getPartType() {
        return partType;
    }

    /**
     * Sets the value of the partType property.
     * 
     * @param value
     *     allowed object is
     *     {@link CsAddressPartType }
     *     
     */
    public void setPartType(CsAddressPartType value) {
        this.partType = value;
    }
    
    public String toString() {
    	return reference.getValue();
    }

}
