//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.15 at 03:22:47 PM GMT 
//


package uk.nhs.ctp.service.report.org.hl7.v3;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CDAAdministrationType_displayName.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CDAAdministrationType_displayName">
 *   &lt;restriction base="{urn:hl7-org:v3}st">
 *     &lt;enumeration value="administration of a dose"/>
 *     &lt;enumeration value="administration of a complete course"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "CDAAdministrationType_displayName")
@XmlEnum
public enum CDAAdministrationTypeDisplayName {

    @XmlEnumValue("administration of a dose")
    ADMINISTRATION_OF_A_DOSE("administration of a dose"),
    @XmlEnumValue("administration of a complete course")
    ADMINISTRATION_OF_A_COMPLETE_COURSE("administration of a complete course");
    private final String value;

    CDAAdministrationTypeDisplayName(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CDAAdministrationTypeDisplayName fromValue(String v) {
        for (CDAAdministrationTypeDisplayName c: CDAAdministrationTypeDisplayName.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
