//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.15 at 03:22:47 PM GMT 
//


package uk.nhs.ctp.service.report.org.hl7.v3;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CDAObservationType_displayName.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CDAObservationType_displayName">
 *   &lt;restriction base="{urn:hl7-org:v3}st">
 *     &lt;enumeration value="ReAdmission Flag"/>
 *     &lt;enumeration value="Last Assessment Review"/>
 *     &lt;enumeration value="Planned Assessment Review"/>
 *     &lt;enumeration value="Copy Provided Flag"/>
 *     &lt;enumeration value="Care Plan Agreement"/>
 *     &lt;enumeration value="Component Planned End Date"/>
 *     &lt;enumeration value="Next Component Review"/>
 *     &lt;enumeration value="Last Component Review"/>
 *     &lt;enumeration value="CAF Information Set"/>
 *     &lt;enumeration value="Component Text Heading Type"/>
 *     &lt;enumeration value="Estimated Discharge Date"/>
 *     &lt;enumeration value="Last Care Plan Review"/>
 *     &lt;enumeration value="Next Care Plan Review"/>
 *     &lt;enumeration value="Text Heading Type"/>
 *     &lt;enumeration value="Procedure Date Reported"/>
 *     &lt;enumeration value="DI Report Status"/>
 *     &lt;enumeration value="Diagnostic Imaging Urgency Indicator"/>
 *     &lt;enumeration value="Next Mental Health Act Tribunal Date"/>
 *     &lt;enumeration value="At Risk Register Entry"/>
 *     &lt;enumeration value="ProtectionRegisterCategory"/>
 *     &lt;enumeration value="Care Process Date Commenced or First Review"/>
 *     &lt;enumeration value="Care Process Date Concluded or Most Recent Review"/>
 *     &lt;enumeration value="Care Process Administration"/>
 *     &lt;enumeration value="Care Review Administration"/>
 *     &lt;enumeration value="Care Process Date of Previous Review"/>
 *     &lt;enumeration value="Care Process Date of Next Planned Review"/>
 *     &lt;enumeration value="Other Entity Associated With Patient"/>
 *     &lt;enumeration value="Care Review Status"/>
 *     &lt;enumeration value="Sampling Frequency"/>
 *     &lt;enumeration value="Device Measurement Range Physical Quantity"/>
 *     &lt;enumeration value="Device Measurement Range String"/>
 *     &lt;enumeration value="Device Resolution Physical Quantity"/>
 *     &lt;enumeration value="Device Resolution String"/>
 *     &lt;enumeration value="Device Accuracy Physical Quantity"/>
 *     &lt;enumeration value="Device Accuracy String"/>
 *     &lt;enumeration value="Waveform Sample Period Observation"/>
 *     &lt;enumeration value="Test Result Observation Series"/>
 *     &lt;enumeration value="Blood Pressure Observation Series"/>
 *     &lt;enumeration value="BMI Observation Series"/>
 *     &lt;enumeration value="Mean Blood Pressure Observation Series"/>
 *     &lt;enumeration value="Temperature Observation Series"/>
 *     &lt;enumeration value="Height Observation Series"/>
 *     &lt;enumeration value="Weight Observation Series"/>
 *     &lt;enumeration value="Pulse Observation Series"/>
 *     &lt;enumeration value="Threshold"/>
 *     &lt;enumeration value="Threshold Rate"/>
 *     &lt;enumeration value="Checklist Outcome"/>
 *     &lt;enumeration value="DST Outcome"/>
 *     &lt;enumeration value="CHC Referral Status"/>
 *     &lt;enumeration value="Permission To View"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "CDAObservationType_displayName")
@XmlEnum
public enum CDAObservationTypeDisplayName {

    @XmlEnumValue("ReAdmission Flag")
    RE_ADMISSION_FLAG("ReAdmission Flag"),
    @XmlEnumValue("Last Assessment Review")
    LAST_ASSESSMENT_REVIEW("Last Assessment Review"),
    @XmlEnumValue("Planned Assessment Review")
    PLANNED_ASSESSMENT_REVIEW("Planned Assessment Review"),
    @XmlEnumValue("Copy Provided Flag")
    COPY_PROVIDED_FLAG("Copy Provided Flag"),
    @XmlEnumValue("Care Plan Agreement")
    CARE_PLAN_AGREEMENT("Care Plan Agreement"),
    @XmlEnumValue("Component Planned End Date")
    COMPONENT_PLANNED_END_DATE("Component Planned End Date"),
    @XmlEnumValue("Next Component Review")
    NEXT_COMPONENT_REVIEW("Next Component Review"),
    @XmlEnumValue("Last Component Review")
    LAST_COMPONENT_REVIEW("Last Component Review"),
    @XmlEnumValue("CAF Information Set")
    CAF_INFORMATION_SET("CAF Information Set"),
    @XmlEnumValue("Component Text Heading Type")
    COMPONENT_TEXT_HEADING_TYPE("Component Text Heading Type"),
    @XmlEnumValue("Estimated Discharge Date")
    ESTIMATED_DISCHARGE_DATE("Estimated Discharge Date"),
    @XmlEnumValue("Last Care Plan Review")
    LAST_CARE_PLAN_REVIEW("Last Care Plan Review"),
    @XmlEnumValue("Next Care Plan Review")
    NEXT_CARE_PLAN_REVIEW("Next Care Plan Review"),
    @XmlEnumValue("Text Heading Type")
    TEXT_HEADING_TYPE("Text Heading Type"),
    @XmlEnumValue("Procedure Date Reported")
    PROCEDURE_DATE_REPORTED("Procedure Date Reported"),
    @XmlEnumValue("DI Report Status")
    DI_REPORT_STATUS("DI Report Status"),
    @XmlEnumValue("Diagnostic Imaging Urgency Indicator")
    DIAGNOSTIC_IMAGING_URGENCY_INDICATOR("Diagnostic Imaging Urgency Indicator"),
    @XmlEnumValue("Next Mental Health Act Tribunal Date")
    NEXT_MENTAL_HEALTH_ACT_TRIBUNAL_DATE("Next Mental Health Act Tribunal Date"),
    @XmlEnumValue("At Risk Register Entry")
    AT_RISK_REGISTER_ENTRY("At Risk Register Entry"),
    @XmlEnumValue("ProtectionRegisterCategory")
    PROTECTION_REGISTER_CATEGORY("ProtectionRegisterCategory"),
    @XmlEnumValue("Care Process Date Commenced or First Review")
    CARE_PROCESS_DATE_COMMENCED_OR_FIRST_REVIEW("Care Process Date Commenced or First Review"),
    @XmlEnumValue("Care Process Date Concluded or Most Recent Review")
    CARE_PROCESS_DATE_CONCLUDED_OR_MOST_RECENT_REVIEW("Care Process Date Concluded or Most Recent Review"),
    @XmlEnumValue("Care Process Administration")
    CARE_PROCESS_ADMINISTRATION("Care Process Administration"),
    @XmlEnumValue("Care Review Administration")
    CARE_REVIEW_ADMINISTRATION("Care Review Administration"),
    @XmlEnumValue("Care Process Date of Previous Review")
    CARE_PROCESS_DATE_OF_PREVIOUS_REVIEW("Care Process Date of Previous Review"),
    @XmlEnumValue("Care Process Date of Next Planned Review")
    CARE_PROCESS_DATE_OF_NEXT_PLANNED_REVIEW("Care Process Date of Next Planned Review"),
    @XmlEnumValue("Other Entity Associated With Patient")
    OTHER_ENTITY_ASSOCIATED_WITH_PATIENT("Other Entity Associated With Patient"),
    @XmlEnumValue("Care Review Status")
    CARE_REVIEW_STATUS("Care Review Status"),
    @XmlEnumValue("Sampling Frequency")
    SAMPLING_FREQUENCY("Sampling Frequency"),
    @XmlEnumValue("Device Measurement Range Physical Quantity")
    DEVICE_MEASUREMENT_RANGE_PHYSICAL_QUANTITY("Device Measurement Range Physical Quantity"),
    @XmlEnumValue("Device Measurement Range String")
    DEVICE_MEASUREMENT_RANGE_STRING("Device Measurement Range String"),
    @XmlEnumValue("Device Resolution Physical Quantity")
    DEVICE_RESOLUTION_PHYSICAL_QUANTITY("Device Resolution Physical Quantity"),
    @XmlEnumValue("Device Resolution String")
    DEVICE_RESOLUTION_STRING("Device Resolution String"),
    @XmlEnumValue("Device Accuracy Physical Quantity")
    DEVICE_ACCURACY_PHYSICAL_QUANTITY("Device Accuracy Physical Quantity"),
    @XmlEnumValue("Device Accuracy String")
    DEVICE_ACCURACY_STRING("Device Accuracy String"),
    @XmlEnumValue("Waveform Sample Period Observation")
    WAVEFORM_SAMPLE_PERIOD_OBSERVATION("Waveform Sample Period Observation"),
    @XmlEnumValue("Test Result Observation Series")
    TEST_RESULT_OBSERVATION_SERIES("Test Result Observation Series"),
    @XmlEnumValue("Blood Pressure Observation Series")
    BLOOD_PRESSURE_OBSERVATION_SERIES("Blood Pressure Observation Series"),
    @XmlEnumValue("BMI Observation Series")
    BMI_OBSERVATION_SERIES("BMI Observation Series"),
    @XmlEnumValue("Mean Blood Pressure Observation Series")
    MEAN_BLOOD_PRESSURE_OBSERVATION_SERIES("Mean Blood Pressure Observation Series"),
    @XmlEnumValue("Temperature Observation Series")
    TEMPERATURE_OBSERVATION_SERIES("Temperature Observation Series"),
    @XmlEnumValue("Height Observation Series")
    HEIGHT_OBSERVATION_SERIES("Height Observation Series"),
    @XmlEnumValue("Weight Observation Series")
    WEIGHT_OBSERVATION_SERIES("Weight Observation Series"),
    @XmlEnumValue("Pulse Observation Series")
    PULSE_OBSERVATION_SERIES("Pulse Observation Series"),
    @XmlEnumValue("Threshold")
    THRESHOLD("Threshold"),
    @XmlEnumValue("Threshold Rate")
    THRESHOLD_RATE("Threshold Rate"),
    @XmlEnumValue("Checklist Outcome")
    CHECKLIST_OUTCOME("Checklist Outcome"),
    @XmlEnumValue("DST Outcome")
    DST_OUTCOME("DST Outcome"),
    @XmlEnumValue("CHC Referral Status")
    CHC_REFERRAL_STATUS("CHC Referral Status"),
    @XmlEnumValue("Permission To View")
    PERMISSION_TO_VIEW("Permission To View");
    private final String value;

    CDAObservationTypeDisplayName(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CDAObservationTypeDisplayName fromValue(String v) {
        for (CDAObservationTypeDisplayName c: CDAObservationTypeDisplayName.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
