//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.15 at 03:22:47 PM GMT 
//


package uk.nhs.ctp.service.report.org.hl7.v3;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CHLCareDomain_displayName.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CHLCareDomain_displayName">
 *   &lt;restriction base="{urn:hl7-org:v3}st">
 *     &lt;enumeration value="Behaviour"/>
 *     &lt;enumeration value="Cognition"/>
 *     &lt;enumeration value="Psychological/Emotional"/>
 *     &lt;enumeration value="Communication"/>
 *     &lt;enumeration value="Mobility"/>
 *     &lt;enumeration value="Nutrition"/>
 *     &lt;enumeration value="Continence"/>
 *     &lt;enumeration value="Skin integrity"/>
 *     &lt;enumeration value="Breathing"/>
 *     &lt;enumeration value="Drug therapies and medication/ symptom control "/>
 *     &lt;enumeration value="Altered states of consciousness"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "CHLCareDomain_displayName")
@XmlEnum
public enum CHLCareDomainDisplayName {

    @XmlEnumValue("Behaviour")
    BEHAVIOUR("Behaviour"),
    @XmlEnumValue("Cognition")
    COGNITION("Cognition"),
    @XmlEnumValue("Psychological/Emotional")
    PSYCHOLOGICAL_EMOTIONAL("Psychological/Emotional"),
    @XmlEnumValue("Communication")
    COMMUNICATION("Communication"),
    @XmlEnumValue("Mobility")
    MOBILITY("Mobility"),
    @XmlEnumValue("Nutrition")
    NUTRITION("Nutrition"),
    @XmlEnumValue("Continence")
    CONTINENCE("Continence"),
    @XmlEnumValue("Skin integrity")
    SKIN_INTEGRITY("Skin integrity"),
    @XmlEnumValue("Breathing")
    BREATHING("Breathing"),
    @XmlEnumValue("Drug therapies and medication/ symptom control ")
    DRUG_THERAPIES_AND_MEDICATION_SYMPTOM_CONTROL("Drug therapies and medication/ symptom control "),
    @XmlEnumValue("Altered states of consciousness")
    ALTERED_STATES_OF_CONSCIOUSNESS("Altered states of consciousness");
    private final String value;

    CHLCareDomainDisplayName(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CHLCareDomainDisplayName fromValue(String v) {
        for (CHLCareDomainDisplayName c: CHLCareDomainDisplayName.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
