//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.30 at 04:13:56 PM BST 
//


package uk.nhs.ctp.service.report.org.hl7.v3;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for COCD_TP146312GB01.Finding complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="COCD_TP146312GB01.Finding">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{urn:hl7-org:v3}InfrastructureRootElements"/>
 *         &lt;element name="code" type="{urn:hl7-org:v3}CD.NPfIT.CDA.Url"/>
 *         &lt;element name="effectiveTime" type="{urn:hl7-org:v3}IVL_TS"/>
 *         &lt;element name="id" type="{urn:hl7-org:v3}II.NPfIT.uuid.mandatory"/>
 *         &lt;element name="interpretationCode" type="{urn:hl7-org:v3}CS" minOccurs="0"/>
 *         &lt;element name="statusCode">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{urn:hl7-org:v3}CS">
 *                 &lt;attribute name="code" use="required">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{urn:hl7-org:v3}cs">
 *                       &lt;enumeration value="nullified"/>
 *                       &lt;enumeration value="completed"/>
 *                       &lt;enumeration value="active"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="templateId">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{urn:hl7-org:v3}II">
 *                 &lt;attribute name="root" use="required">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{urn:hl7-org:v3}uid">
 *                       &lt;enumeration value="2.16.840.1.113883.2.1.3.2.4.18.2"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *                 &lt;attribute name="extension" use="required">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{urn:hl7-org:v3}st">
 *                       &lt;enumeration value="COCD_TP146312GB01#Finding"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="value" type="{urn:hl7-org:v3}ANY" minOccurs="0"/>
 *         &lt;element name="author" type="{urn:hl7-org:v3}COCD_TP146312GB01.Author1" minOccurs="0"/>
 *         &lt;element name="informant" type="{urn:hl7-org:v3}COCD_TP146312GB01.Informant" minOccurs="0"/>
 *         &lt;element name="performer" type="{urn:hl7-org:v3}COCD_TP146312GB01.Performer" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="referenceRange" type="{urn:hl7-org:v3}COCD_TP146312GB01.ReferenceRange" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{urn:hl7-org:v3}InfrastructureRootAttributes"/>
 *       &lt;attribute name="classCode" use="required" type="{urn:hl7-org:v3}cs" fixed="OBS" />
 *       &lt;attribute name="moodCode" use="required" type="{urn:hl7-org:v3}x_ActMoodDocumentObservation" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "COCD_TP146312GB01.Finding", propOrder = {
    "code",
    "effectiveTime",
    "id",
    "interpretationCode",
    "statusCode",
    "templateId",
    "value"
})
public class COCDTP146312GB01Finding {

    @XmlElement(required = true)
    protected CDNPfITCDAUrl code;
    @XmlElement(required = true)
    protected IVLTS effectiveTime;
    @XmlElement(required = true)
    protected IINPfITUuidMandatory id;
    protected CS interpretationCode;
    @XmlElement(required = true)
    protected COCDTP146312GB01Finding.StatusCode statusCode;
    @XmlElement(required = true)
    protected COCDTP146312GB01Finding.TemplateId templateId;
    protected ANY value;
//    @XmlElementRef(name = "author", namespace = "urn:hl7-org:v3", type = JAXBElement.class, required = false)
//    protected JAXBElement<POCDMT200001GB02Author> author;
//    @XmlElementRef(name = "informant", namespace = "urn:hl7-org:v3", type = JAXBElement.class, required = false)
//    protected JAXBElement<COCDTP146312GB01Informant> informant;
//    @XmlElement(nillable = true)
//    protected List<COCDTP146312GB01Performer> performer;
//    @XmlElementRef(name = "referenceRange", namespace = "urn:hl7-org:v3", type = JAXBElement.class, required = false)
//    protected JAXBElement<COCDTP146312GB01ReferenceRange> referenceRange;
    @XmlAttribute(name = "classCode", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String classCode;
    @XmlAttribute(name = "moodCode", required = true)
    protected XActMoodDocumentObservation moodCode;
    @XmlAttribute(name = "nullFlavor")
    protected List<String> nullFlavor;
    @XmlAttribute(name = "updateMode")
    protected CsUpdateMode updateMode;

    /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link CDNPfITCDAUrl }
     *     
     */
    public CDNPfITCDAUrl getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link CDNPfITCDAUrl }
     *     
     */
    public void setCode(CDNPfITCDAUrl value) {
        this.code = value;
    }

    /**
     * Gets the value of the effectiveTime property.
     * 
     * @return
     *     possible object is
     *     {@link IVLTS }
     *     
     */
    public IVLTS getEffectiveTime() {
        return effectiveTime;
    }

    /**
     * Sets the value of the effectiveTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link IVLTS }
     *     
     */
    public void setEffectiveTime(IVLTS value) {
        this.effectiveTime = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link IINPfITUuidMandatory }
     *     
     */
    public IINPfITUuidMandatory getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link IINPfITUuidMandatory }
     *     
     */
    public void setId(IINPfITUuidMandatory value) {
        this.id = value;
    }

    /**
     * Gets the value of the interpretationCode property.
     * 
     * @return
     *     possible object is
     *     {@link CS }
     *     
     */
    public CS getInterpretationCode() {
        return interpretationCode;
    }

    /**
     * Sets the value of the interpretationCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link CS }
     *     
     */
    public void setInterpretationCode(CS value) {
        this.interpretationCode = value;
    }

    /**
     * Gets the value of the statusCode property.
     * 
     * @return
     *     possible object is
     *     {@link COCDTP146312GB01Finding.StatusCode }
     *     
     */
    public COCDTP146312GB01Finding.StatusCode getStatusCode() {
        return statusCode;
    }

    /**
     * Sets the value of the statusCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link COCDTP146312GB01Finding.StatusCode }
     *     
     */
    public void setStatusCode(COCDTP146312GB01Finding.StatusCode value) {
        this.statusCode = value;
    }

    /**
     * Gets the value of the templateId property.
     * 
     * @return
     *     possible object is
     *     {@link COCDTP146312GB01Finding.TemplateId }
     *     
     */
    public COCDTP146312GB01Finding.TemplateId getTemplateId() {
        return templateId;
    }

    /**
     * Sets the value of the templateId property.
     * 
     * @param value
     *     allowed object is
     *     {@link COCDTP146312GB01Finding.TemplateId }
     *     
     */
    public void setTemplateId(COCDTP146312GB01Finding.TemplateId value) {
        this.templateId = value;
    }

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link ANY }
     *     
     */
    public ANY getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link ANY }
     *     
     */
    public void setValue(ANY value) {
        this.value = value;
    }

//    /**
//     * Gets the value of the author property.
//     * 
//     * @return
//     *     possible object is
//     *     {@link JAXBElement }{@code <}{@link COCDTP146312GB01Author1 }{@code >}
//     *     
//     */
//    public JAXBElement<COCDTP146312GB01Author1> getAuthor() {
//        return author;
//    }
//
//    /**
//     * Sets the value of the author property.
//     * 
//     * @param value
//     *     allowed object is
//     *     {@link JAXBElement }{@code <}{@link COCDTP146312GB01Author1 }{@code >}
//     *     
//     */
//    public void setAuthor(JAXBElement<COCDTP146312GB01Author1> value) {
//        this.author = value;
//    }
//
//    /**
//     * Gets the value of the informant property.
//     * 
//     * @return
//     *     possible object is
//     *     {@link JAXBElement }{@code <}{@link COCDTP146312GB01Informant }{@code >}
//     *     
//     */
//    public JAXBElement<COCDTP146312GB01Informant> getInformant() {
//        return informant;
//    }
//
//    /**
//     * Sets the value of the informant property.
//     * 
//     * @param value
//     *     allowed object is
//     *     {@link JAXBElement }{@code <}{@link COCDTP146312GB01Informant }{@code >}
//     *     
//     */
//    public void setInformant(JAXBElement<COCDTP146312GB01Informant> value) {
//        this.informant = value;
//    }
//
//    /**
//     * Gets the value of the performer property.
//     * 
//     * <p>
//     * This accessor method returns a reference to the live list,
//     * not a snapshot. Therefore any modification you make to the
//     * returned list will be present inside the JAXB object.
//     * This is why there is not a <CODE>set</CODE> method for the performer property.
//     * 
//     * <p>
//     * For example, to add a new item, do as follows:
//     * <pre>
//     *    getPerformer().add(newItem);
//     * </pre>
//     * 
//     * 
//     * <p>
//     * Objects of the following type(s) are allowed in the list
//     * {@link COCDTP146312GB01Performer }
//     * 
//     * 
//     */
//    public List<COCDTP146312GB01Performer> getPerformer() {
//        if (performer == null) {
//            performer = new ArrayList<COCDTP146312GB01Performer>();
//        }
//        return this.performer;
//    }
//
//    /**
//     * Gets the value of the referenceRange property.
//     * 
//     * @return
//     *     possible object is
//     *     {@link JAXBElement }{@code <}{@link COCDTP146312GB01ReferenceRange }{@code >}
//     *     
//     */
//    public JAXBElement<COCDTP146312GB01ReferenceRange> getReferenceRange() {
//        return referenceRange;
//    }
//
//    /**
//     * Sets the value of the referenceRange property.
//     * 
//     * @param value
//     *     allowed object is
//     *     {@link JAXBElement }{@code <}{@link COCDTP146312GB01ReferenceRange }{@code >}
//     *     
//     */
//    public void setReferenceRange(JAXBElement<COCDTP146312GB01ReferenceRange> value) {
//        this.referenceRange = value;
//    }

    /**
     * Gets the value of the classCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClassCode() {
        if (classCode == null) {
            return "OBS";
        } else {
            return classCode;
        }
    }

    /**
     * Sets the value of the classCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClassCode(String value) {
        this.classCode = value;
    }

    /**
     * Gets the value of the moodCode property.
     * 
     * @return
     *     possible object is
     *     {@link XActMoodDocumentObservation }
     *     
     */
    public XActMoodDocumentObservation getMoodCode() {
        return moodCode;
    }

    /**
     * Sets the value of the moodCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link XActMoodDocumentObservation }
     *     
     */
    public void setMoodCode(XActMoodDocumentObservation value) {
        this.moodCode = value;
    }

    /**
     * Gets the value of the nullFlavor property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the nullFlavor property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNullFlavor().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getNullFlavor() {
        if (nullFlavor == null) {
            nullFlavor = new ArrayList<String>();
        }
        return this.nullFlavor;
    }

    /**
     * Gets the value of the updateMode property.
     * 
     * @return
     *     possible object is
     *     {@link CsUpdateMode }
     *     
     */
    public CsUpdateMode getUpdateMode() {
        return updateMode;
    }

    /**
     * Sets the value of the updateMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link CsUpdateMode }
     *     
     */
    public void setUpdateMode(CsUpdateMode value) {
        this.updateMode = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{urn:hl7-org:v3}CS">
     *       &lt;attribute name="code" use="required">
     *         &lt;simpleType>
     *           &lt;restriction base="{urn:hl7-org:v3}cs">
     *             &lt;enumeration value="nullified"/>
     *             &lt;enumeration value="completed"/>
     *             &lt;enumeration value="active"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class StatusCode
        extends CS
    {


    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{urn:hl7-org:v3}II">
     *       &lt;attribute name="root" use="required">
     *         &lt;simpleType>
     *           &lt;restriction base="{urn:hl7-org:v3}uid">
     *             &lt;enumeration value="2.16.840.1.113883.2.1.3.2.4.18.2"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *       &lt;attribute name="extension" use="required">
     *         &lt;simpleType>
     *           &lt;restriction base="{urn:hl7-org:v3}st">
     *             &lt;enumeration value="COCD_TP146312GB01#Finding"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class TemplateId
        extends II
    {


    }

}
