//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.15 at 03:22:47 PM GMT 
//


package uk.nhs.ctp.service.report.org.hl7.v3;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import uk.nhs.ctp.service.report.npfit.hl7.localisation.TemplateContent;


/**
 * <p>Java class for COCD_TP146246GB01.Author_1 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="COCD_TP146246GB01.Author_1">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{urn:hl7-org:v3}InfrastructureRootElements"/>
 *         &lt;element ref="{NPFIT:HL7:Localisation}contentId"/>
 *         &lt;element name="functionCode">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{urn:hl7-org:v3}CV">
 *                 &lt;attribute name="code" use="required" type="{urn:hl7-org:v3}cs" fixed="OA" />
 *                 &lt;attribute name="displayName" use="required" type="{urn:hl7-org:v3}st" fixed="Originating Author" />
 *                 &lt;attribute name="codeSystem" use="required" type="{urn:hl7-org:v3}uid" fixed="2.16.840.1.113883.2.1.3.2.4.17.178" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="templateId">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{urn:hl7-org:v3}II">
 *                 &lt;attribute name="root" use="required">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{urn:hl7-org:v3}uid">
 *                       &lt;enumeration value="2.16.840.1.113883.2.1.3.2.4.18.2"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *                 &lt;attribute name="extension" use="required">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{urn:hl7-org:v3}st">
 *                       &lt;enumeration value="COCD_TP146246GB01#author"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="time">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{urn:hl7-org:v3}TS">
 *                 &lt;attribute name="value" use="required" type="{urn:hl7-org:v3}ts" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;choice>
 *           &lt;group ref="{urn:hl7-org:v3}NPFIT-000081_Role"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{urn:hl7-org:v3}InfrastructureRootAttributes"/>
 *       &lt;attribute name="typeCode" use="required" type="{urn:hl7-org:v3}cs" fixed="AUT" />
 *       &lt;attribute name="contextControlCode" use="required" type="{urn:hl7-org:v3}ContextControl" fixed="OP" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "COCD_TP146246GB01.Author_1", propOrder = {
    "contentId",
    "functionCode",
    "templateId",
    "time",
    "cocdtp145200GB01AssignedAuthor",
    "cocdtp145208GB01AssignedAuthor",
    "cocdtp145212GB02Workgroup",
    "cocdtp145207GB01AssignedAuthorDevice"
})
public class COCDTP146246GB01Author1 {

    @XmlElement(namespace = "NPFIT:HL7:Localisation", required = true)
    protected TemplateContent contentId;
    @XmlElement(required = true)
    protected COCDTP146246GB01Author1 .FunctionCode functionCode;
    @XmlElement(required = true)
    protected COCDTP146246GB01Author1 .TemplateId templateId;
    @XmlElement(required = true)
    protected COCDTP146246GB01Author1 .Time time;
    @XmlElement(name = "COCD_TP145200GB01.AssignedAuthor")
    protected COCDTP145200GB01AssignedAuthor cocdtp145200GB01AssignedAuthor;
    @XmlElement(name = "COCD_TP145208GB01.AssignedAuthor")
    protected COCDTP145208GB01AssignedAuthor cocdtp145208GB01AssignedAuthor;
    @XmlElement(name = "COCD_TP145212GB02.Workgroup")
    protected COCDTP145212GB02Workgroup cocdtp145212GB02Workgroup;
    @XmlElement(name = "COCD_TP145207GB01.AssignedAuthorDevice")
    protected COCDTP145207GB01AssignedAuthorDevice cocdtp145207GB01AssignedAuthorDevice;
    @XmlAttribute(name = "typeCode", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String typeCode;
    @XmlAttribute(name = "contextControlCode", required = true)
    protected List<String> contextControlCode;
    @XmlAttribute(name = "nullFlavor")
    protected List<String> nullFlavor;
    @XmlAttribute(name = "updateMode")
    protected CsUpdateMode updateMode;

    /**
     * Gets the value of the contentId property.
     * 
     * @return
     *     possible object is
     *     {@link TemplateContent }
     *     
     */
    public TemplateContent getContentId() {
        return contentId;
    }

    /**
     * Sets the value of the contentId property.
     * 
     * @param value
     *     allowed object is
     *     {@link TemplateContent }
     *     
     */
    public void setContentId(TemplateContent value) {
        this.contentId = value;
    }

    /**
     * Gets the value of the functionCode property.
     * 
     * @return
     *     possible object is
     *     {@link COCDTP146246GB01Author1 .FunctionCode }
     *     
     */
    public COCDTP146246GB01Author1 .FunctionCode getFunctionCode() {
        return functionCode;
    }

    /**
     * Sets the value of the functionCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link COCDTP146246GB01Author1 .FunctionCode }
     *     
     */
    public void setFunctionCode(COCDTP146246GB01Author1 .FunctionCode value) {
        this.functionCode = value;
    }

    /**
     * Gets the value of the templateId property.
     * 
     * @return
     *     possible object is
     *     {@link COCDTP146246GB01Author1 .TemplateId }
     *     
     */
    public COCDTP146246GB01Author1 .TemplateId getTemplateId() {
        return templateId;
    }

    /**
     * Sets the value of the templateId property.
     * 
     * @param value
     *     allowed object is
     *     {@link COCDTP146246GB01Author1 .TemplateId }
     *     
     */
    public void setTemplateId(COCDTP146246GB01Author1 .TemplateId value) {
        this.templateId = value;
    }

    /**
     * Gets the value of the time property.
     * 
     * @return
     *     possible object is
     *     {@link COCDTP146246GB01Author1 .Time }
     *     
     */
    public COCDTP146246GB01Author1 .Time getTime() {
        return time;
    }

    /**
     * Sets the value of the time property.
     * 
     * @param value
     *     allowed object is
     *     {@link COCDTP146246GB01Author1 .Time }
     *     
     */
    public void setTime(COCDTP146246GB01Author1 .Time value) {
        this.time = value;
    }

    /**
     * Gets the value of the cocdtp145200GB01AssignedAuthor property.
     * 
     * @return
     *     possible object is
     *     {@link COCDTP145200GB01AssignedAuthor }
     *     
     */
    public COCDTP145200GB01AssignedAuthor getCOCDTP145200GB01AssignedAuthor() {
        return cocdtp145200GB01AssignedAuthor;
    }

    /**
     * Sets the value of the cocdtp145200GB01AssignedAuthor property.
     * 
     * @param value
     *     allowed object is
     *     {@link COCDTP145200GB01AssignedAuthor }
     *     
     */
    public void setCOCDTP145200GB01AssignedAuthor(COCDTP145200GB01AssignedAuthor value) {
        this.cocdtp145200GB01AssignedAuthor = value;
    }

    /**
     * Gets the value of the cocdtp145208GB01AssignedAuthor property.
     * 
     * @return
     *     possible object is
     *     {@link COCDTP145208GB01AssignedAuthor }
     *     
     */
    public COCDTP145208GB01AssignedAuthor getCOCDTP145208GB01AssignedAuthor() {
        return cocdtp145208GB01AssignedAuthor;
    }

    /**
     * Sets the value of the cocdtp145208GB01AssignedAuthor property.
     * 
     * @param value
     *     allowed object is
     *     {@link COCDTP145208GB01AssignedAuthor }
     *     
     */
    public void setCOCDTP145208GB01AssignedAuthor(COCDTP145208GB01AssignedAuthor value) {
        this.cocdtp145208GB01AssignedAuthor = value;
    }

    /**
     * Gets the value of the cocdtp145212GB02Workgroup property.
     * 
     * @return
     *     possible object is
     *     {@link COCDTP145212GB02Workgroup }
     *     
     */
    public COCDTP145212GB02Workgroup getCOCDTP145212GB02Workgroup() {
        return cocdtp145212GB02Workgroup;
    }

    /**
     * Sets the value of the cocdtp145212GB02Workgroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link COCDTP145212GB02Workgroup }
     *     
     */
    public void setCOCDTP145212GB02Workgroup(COCDTP145212GB02Workgroup value) {
        this.cocdtp145212GB02Workgroup = value;
    }

    /**
     * Gets the value of the cocdtp145207GB01AssignedAuthorDevice property.
     * 
     * @return
     *     possible object is
     *     {@link COCDTP145207GB01AssignedAuthorDevice }
     *     
     */
    public COCDTP145207GB01AssignedAuthorDevice getCOCDTP145207GB01AssignedAuthorDevice() {
        return cocdtp145207GB01AssignedAuthorDevice;
    }

    /**
     * Sets the value of the cocdtp145207GB01AssignedAuthorDevice property.
     * 
     * @param value
     *     allowed object is
     *     {@link COCDTP145207GB01AssignedAuthorDevice }
     *     
     */
    public void setCOCDTP145207GB01AssignedAuthorDevice(COCDTP145207GB01AssignedAuthorDevice value) {
        this.cocdtp145207GB01AssignedAuthorDevice = value;
    }

    /**
     * Gets the value of the typeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTypeCode() {
        if (typeCode == null) {
            return "AUT";
        } else {
            return typeCode;
        }
    }

    /**
     * Sets the value of the typeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypeCode(String value) {
        this.typeCode = value;
    }

    /**
     * Gets the value of the contextControlCode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the contextControlCode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContextControlCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getContextControlCode() {
        if (contextControlCode == null) {
            contextControlCode = new ArrayList<String>();
        }
        return this.contextControlCode;
    }

    /**
     * Gets the value of the nullFlavor property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the nullFlavor property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNullFlavor().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getNullFlavor() {
        if (nullFlavor == null) {
            nullFlavor = new ArrayList<String>();
        }
        return this.nullFlavor;
    }

    /**
     * Gets the value of the updateMode property.
     * 
     * @return
     *     possible object is
     *     {@link CsUpdateMode }
     *     
     */
    public CsUpdateMode getUpdateMode() {
        return updateMode;
    }

    /**
     * Sets the value of the updateMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link CsUpdateMode }
     *     
     */
    public void setUpdateMode(CsUpdateMode value) {
        this.updateMode = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{urn:hl7-org:v3}CV">
     *       &lt;attribute name="code" use="required" type="{urn:hl7-org:v3}cs" fixed="OA" />
     *       &lt;attribute name="displayName" use="required" type="{urn:hl7-org:v3}st" fixed="Originating Author" />
     *       &lt;attribute name="codeSystem" use="required" type="{urn:hl7-org:v3}uid" fixed="2.16.840.1.113883.2.1.3.2.4.17.178" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class FunctionCode
        extends CV
    {


    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{urn:hl7-org:v3}II">
     *       &lt;attribute name="root" use="required">
     *         &lt;simpleType>
     *           &lt;restriction base="{urn:hl7-org:v3}uid">
     *             &lt;enumeration value="2.16.840.1.113883.2.1.3.2.4.18.2"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *       &lt;attribute name="extension" use="required">
     *         &lt;simpleType>
     *           &lt;restriction base="{urn:hl7-org:v3}st">
     *             &lt;enumeration value="COCD_TP146246GB01#author"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class TemplateId
        extends II
    {


    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{urn:hl7-org:v3}TS">
     *       &lt;attribute name="value" use="required" type="{urn:hl7-org:v3}ts" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Time
        extends TS
    {


    }

}
