//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.15 at 03:22:47 PM GMT 
//


package uk.nhs.ctp.service.report.org.hl7.v3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Coded data, consists of a code, display name, code system, and original text. Used when a single code value must be sent.
 * 
 * <p>Java class for CS complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CS">
 *   &lt;complexContent>
 *     &lt;restriction base="{urn:hl7-org:v3}CV">
 *       &lt;sequence>
 *       &lt;/sequence>
 *       &lt;attribute name="code" type="{urn:hl7-org:v3}cs" />
 *       &lt;attribute name="codeSystem" type="{urn:hl7-org:v3}uid" />
 *       &lt;attribute name="codeSystemName" type="{urn:hl7-org:v3}st" />
 *       &lt;attribute name="codeSystemVersion" type="{urn:hl7-org:v3}st" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CS")
@XmlSeeAlso({
    CSObservationType.class,
    CSDSTOutcomeLevelOfNeed.class,
    CSDSTCareDomain.class,
    CSRequesterRelationshipType.class,
    CSCDAPrescriptionAnnotation.class,
    CSGPESMessageType.class,
    CSAuthorFunctionType.class,
    CSBusinessSectionType.class,
    CSCDAOrganizationType.class,
    CSCDAAdministrationType.class,
   uk.nhs.ctp.service.report.org.hl7.v3.COCDTP146226GB02Consent.StatusCode.class,
    CSCHLOutcomeLevelOfNeed.class,
    CSHealthSpaceBusinessSectionType.class,
    CSSealingActType.class,
    CSCHLOutcome.class,
    CSTriageDispositionType.class,
    CSTriageOutcomeType.class,
    CSCHCCancellationReasonCode.class,
    CSXBasicConfidentialityKind.class,
    CSCHLCareDomain.class,
    CSReasonForDocumentNullification.class,
    CSSealingRefusalReason.class,
    CSActStatus.class,
    CSDSTEligibilityOutcome.class,
    CSCHCRejectionReason.class,
    CSSystemFlagType.class,
    CSCDAActCode.class,
    CSNHS111TriageDeviceType.class,
    CSCDAObservationType.class,
    CSSealEventActionCode.class
})
public class CS
    extends CV
{


}
