//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.15 at 03:22:47 PM GMT 
//


package uk.nhs.ctp.service.report.org.hl7.v3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Coded data, consists of a code, display name, code system, and original text. Used when a single code value must be sent.
 * 
 * <p>Java class for CV complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CV">
 *   &lt;complexContent>
 *     &lt;restriction base="{urn:hl7-org:v3}CE">
 *       &lt;sequence>
 *         &lt;element name="originalText" type="{urn:hl7-org:v3}ED" minOccurs="0"/>
 *         &lt;element name="translation" type="{urn:hl7-org:v3}CD" maxOccurs="0" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="code" type="{urn:hl7-org:v3}cs" />
 *       &lt;attribute name="codeSystem" type="{urn:hl7-org:v3}uid" />
 *       &lt;attribute name="codeSystemName" type="{urn:hl7-org:v3}st" />
 *       &lt;attribute name="codeSystemVersion" type="{urn:hl7-org:v3}st" />
 *       &lt;attribute name="displayName" type="{urn:hl7-org:v3}st" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CV")
@XmlSeeAlso({
    CVObservationType.class,
   uk.nhs.ctp.service.report.org.hl7.v3.COCDTP146050GB01PermissionToView.Code.class,
    CVNPfITCodedplainRequired.class,
   uk.nhs.ctp.service.report.org.hl7.v3.COCDTP146091GB01Author1 .FunctionCode.class,
    CVNHS111TriageDeviceType.class,
    CO.class,
    CVCHCRejectionReason.class,
    CVAuthorFunctionType.class,
   uk.nhs.ctp.service.report.org.hl7.v3.POCDMT200001GB02Author.FunctionCode.class,
    CVNPfITCodedOriginaltext.class,
    CVCHLCareDomain.class,
    CVReasonForDocumentNullification.class,
    CVSystemFlagType.class,
    CVDSTCareDomain.class,
    CVNHS111MessageType.class,
    CVGPESMessageType.class,
    CVNPfITCodedOriginaltextRequired.class,
    CVXBasicConfidentialityKind.class,
    CVRequesterRelationshipType.class,
    CVCDAPrescriptionAnnotation.class,
    CVCHCCancellationReasonCode.class,
    CVNPfITCodedDisplayname.class,
    CVCHLOutcome.class,
    CVSealEventActionCode.class,
    CVCDAObservationType.class,
    CVNPfITCodedCodeSystemRequired.class,
    CVTriageDispositionType.class,
    CVHealthSpaceBusinessSectionType.class,
   uk.nhs.ctp.service.report.org.hl7.v3.COCDTP145202GB02Organization.StandardIndustryClassCode.class,
   uk.nhs.ctp.service.report.org.hl7.v3.COCDTP146246GB01Author1 .FunctionCode.class,
    PQR.class,
    CVCHLOutcomeLevelOfNeed.class,
    CVNPfITCodeonlyRequired.class,
    CVCDAActCode.class,
   uk.nhs.ctp.service.report.org.hl7.v3.COCDTP145000GB01ParticipantRole.Code.class,
    CVNPfITCodedCodeSystem.class,
    CVTriageOutcomeType.class,
    CVDSTEligibilityOutcome.class,
    CVBusinessSectionType.class,
    CVCDAOrganizationType.class,
   uk.nhs.ctp.service.report.org.hl7.v3.COCDTP145203GB03Organization.StandardIndustryClassCode.class,
    CVSealingRefusalReason.class,
    CVNHS111AdditionalNotesType.class,
    CVNPfITCodedplain.class,
    CVSealingActType.class,
    CVNHS111RepeatCallerServiceResponseType.class,
    CVCDAAdministrationType.class,
    CVNPfITCodedDisplaynameRequired.class,
    CVActStatus.class,
    CS.class,
    CVNPfITCodeonly.class,
    CVDSTOutcomeLevelOfNeed.class
})
public class CV
    extends CE
{


}
