//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.15 at 03:22:47 PM GMT 
//


package uk.nhs.ctp.service.report.org.hl7.v3;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DSTCareDomain_displayName.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DSTCareDomain_displayName">
 *   &lt;restriction base="{urn:hl7-org:v3}st">
 *     &lt;enumeration value="Behaviour"/>
 *     &lt;enumeration value="Cognition"/>
 *     &lt;enumeration value="Psychological and Emotional Needs"/>
 *     &lt;enumeration value="Communication"/>
 *     &lt;enumeration value="Mobility"/>
 *     &lt;enumeration value="Nutrition - Food and Drink"/>
 *     &lt;enumeration value="Continence"/>
 *     &lt;enumeration value="Skin (including tissue viability)"/>
 *     &lt;enumeration value="Breathing"/>
 *     &lt;enumeration value="Drug Therapies and Medication - Symptom Control"/>
 *     &lt;enumeration value="Altered States of Consciousness"/>
 *     &lt;enumeration value="Other significant care needs"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "DSTCareDomain_displayName")
@XmlEnum
public enum DSTCareDomainDisplayName {

    @XmlEnumValue("Behaviour")
    BEHAVIOUR("Behaviour"),
    @XmlEnumValue("Cognition")
    COGNITION("Cognition"),
    @XmlEnumValue("Psychological and Emotional Needs")
    PSYCHOLOGICAL_AND_EMOTIONAL_NEEDS("Psychological and Emotional Needs"),
    @XmlEnumValue("Communication")
    COMMUNICATION("Communication"),
    @XmlEnumValue("Mobility")
    MOBILITY("Mobility"),
    @XmlEnumValue("Nutrition - Food and Drink")
    NUTRITION_FOOD_AND_DRINK("Nutrition - Food and Drink"),
    @XmlEnumValue("Continence")
    CONTINENCE("Continence"),
    @XmlEnumValue("Skin (including tissue viability)")
    SKIN_INCLUDING_TISSUE_VIABILITY("Skin (including tissue viability)"),
    @XmlEnumValue("Breathing")
    BREATHING("Breathing"),
    @XmlEnumValue("Drug Therapies and Medication - Symptom Control")
    DRUG_THERAPIES_AND_MEDICATION_SYMPTOM_CONTROL("Drug Therapies and Medication - Symptom Control"),
    @XmlEnumValue("Altered States of Consciousness")
    ALTERED_STATES_OF_CONSCIOUSNESS("Altered States of Consciousness"),
    @XmlEnumValue("Other significant care needs")
    OTHER_SIGNIFICANT_CARE_NEEDS("Other significant care needs");
    private final String value;

    DSTCareDomainDisplayName(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DSTCareDomainDisplayName fromValue(String v) {
        for (DSTCareDomainDisplayName c: DSTCareDomainDisplayName.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
