//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.15 at 03:22:47 PM GMT 
//


package uk.nhs.ctp.service.report.org.hl7.v3;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DSTOutcomeLevelOfNeed_code.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DSTOutcomeLevelOfNeed_code">
 *   &lt;restriction base="{urn:hl7-org:v3}cs">
 *     &lt;enumeration value="Priority"/>
 *     &lt;enumeration value="Severe"/>
 *     &lt;enumeration value="High"/>
 *     &lt;enumeration value="Moderate"/>
 *     &lt;enumeration value="Low"/>
 *     &lt;enumeration value="NoNeeds"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "DSTOutcomeLevelOfNeed_code")
@XmlEnum
public enum DSTOutcomeLevelOfNeedCode {

    @XmlEnumValue("Priority")
    PRIORITY("Priority"),
    @XmlEnumValue("Severe")
    SEVERE("Severe"),
    @XmlEnumValue("High")
    HIGH("High"),
    @XmlEnumValue("Moderate")
    MODERATE("Moderate"),
    @XmlEnumValue("Low")
    LOW("Low"),
    @XmlEnumValue("NoNeeds")
    NO_NEEDS("NoNeeds");
    private final String value;

    DSTOutcomeLevelOfNeedCode(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DSTOutcomeLevelOfNeedCode fromValue(String v) {
        for (DSTOutcomeLevelOfNeedCode c: DSTOutcomeLevelOfNeedCode.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
