//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.15 at 03:22:47 PM GMT 
//


package uk.nhs.ctp.service.report.org.hl7.v3;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DSTOutcomeLevelOfNeed_displayName.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DSTOutcomeLevelOfNeed_displayName">
 *   &lt;restriction base="{urn:hl7-org:v3}st">
 *     &lt;enumeration value="Priority Level of Need Identified"/>
 *     &lt;enumeration value="Severe Level of Need Identified"/>
 *     &lt;enumeration value="High Level of Need Identified"/>
 *     &lt;enumeration value="Some Level of Need Identified"/>
 *     &lt;enumeration value="Low Level of Need Identified"/>
 *     &lt;enumeration value="No Needs Identified"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "DSTOutcomeLevelOfNeed_displayName")
@XmlEnum
public enum DSTOutcomeLevelOfNeedDisplayName {

    @XmlEnumValue("Priority Level of Need Identified")
    PRIORITY_LEVEL_OF_NEED_IDENTIFIED("Priority Level of Need Identified"),
    @XmlEnumValue("Severe Level of Need Identified")
    SEVERE_LEVEL_OF_NEED_IDENTIFIED("Severe Level of Need Identified"),
    @XmlEnumValue("High Level of Need Identified")
    HIGH_LEVEL_OF_NEED_IDENTIFIED("High Level of Need Identified"),
    @XmlEnumValue("Some Level of Need Identified")
    SOME_LEVEL_OF_NEED_IDENTIFIED("Some Level of Need Identified"),
    @XmlEnumValue("Low Level of Need Identified")
    LOW_LEVEL_OF_NEED_IDENTIFIED("Low Level of Need Identified"),
    @XmlEnumValue("No Needs Identified")
    NO_NEEDS_IDENTIFIED("No Needs Identified");
    private final String value;

    DSTOutcomeLevelOfNeedDisplayName(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DSTOutcomeLevelOfNeedDisplayName fromValue(String v) {
        for (DSTOutcomeLevelOfNeedDisplayName c: DSTOutcomeLevelOfNeedDisplayName.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
