//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.30 at 12:27:07 PM BST 
//


package uk.nhs.ctp.service.report.org.hl7.v3;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EoLCDAObservationType_displayName.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="EoLCDAObservationType_displayName">
 *   &lt;restriction base="{urn:hl7-org:v3}st">
 *     &lt;enumeration value="EOL Care Plan"/>
 *     &lt;enumeration value="EOL Tool Used"/>
 *     &lt;enumeration value="EOL Current Stage"/>
 *     &lt;enumeration value="EOL Planned Review Date"/>
 *     &lt;enumeration value="EOL Patient Relationships"/>
 *     &lt;enumeration value="EOL Patient ADRT"/>
 *     &lt;enumeration value="EOL Patient ADRT Docs Location"/>
 *     &lt;enumeration value="EOL Patient ADRT Discussed"/>
 *     &lt;enumeration value="EOL Anticipatory Medicine Box Location"/>
 *     &lt;enumeration value="EOL DNACPR by Senior Responsible Clinician"/>
 *     &lt;enumeration value="EOL DNACPR Docs Location"/>
 *     &lt;enumeration value="EOL Aware of Prognosis"/>
 *     &lt;enumeration value="EOL Authority to LPA"/>
 *     &lt;enumeration value="EOL DNACPR Review Date"/>
 *     &lt;enumeration value="EOL Resuscitation Status"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "EoLCDAObservationType_displayName")
@XmlEnum
public enum EoLCDAObservationTypeDisplayName {

    @XmlEnumValue("EOL Care Plan")
    EOL_CARE_PLAN("EOL Care Plan"),
    @XmlEnumValue("EOL Tool Used")
    EOL_TOOL_USED("EOL Tool Used"),
    @XmlEnumValue("EOL Current Stage")
    EOL_CURRENT_STAGE("EOL Current Stage"),
    @XmlEnumValue("EOL Planned Review Date")
    EOL_PLANNED_REVIEW_DATE("EOL Planned Review Date"),
    @XmlEnumValue("EOL Patient Relationships")
    EOL_PATIENT_RELATIONSHIPS("EOL Patient Relationships"),
    @XmlEnumValue("EOL Patient ADRT")
    EOL_PATIENT_ADRT("EOL Patient ADRT"),
    @XmlEnumValue("EOL Patient ADRT Docs Location")
    EOL_PATIENT_ADRT_DOCS_LOCATION("EOL Patient ADRT Docs Location"),
    @XmlEnumValue("EOL Patient ADRT Discussed")
    EOL_PATIENT_ADRT_DISCUSSED("EOL Patient ADRT Discussed"),
    @XmlEnumValue("EOL Anticipatory Medicine Box Location")
    EOL_ANTICIPATORY_MEDICINE_BOX_LOCATION("EOL Anticipatory Medicine Box Location"),
    @XmlEnumValue("EOL DNACPR by Senior Responsible Clinician")
    EOL_DNACPR_BY_SENIOR_RESPONSIBLE_CLINICIAN("EOL DNACPR by Senior Responsible Clinician"),
    @XmlEnumValue("EOL DNACPR Docs Location")
    EOL_DNACPR_DOCS_LOCATION("EOL DNACPR Docs Location"),
    @XmlEnumValue("EOL Aware of Prognosis")
    EOL_AWARE_OF_PROGNOSIS("EOL Aware of Prognosis"),
    @XmlEnumValue("EOL Authority to LPA")
    EOL_AUTHORITY_TO_LPA("EOL Authority to LPA"),
    @XmlEnumValue("EOL DNACPR Review Date")
    EOL_DNACPR_REVIEW_DATE("EOL DNACPR Review Date"),
    @XmlEnumValue("EOL Resuscitation Status")
    EOL_RESUSCITATION_STATUS("EOL Resuscitation Status");
    private final String value;

    EoLCDAObservationTypeDisplayName(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static EoLCDAObservationTypeDisplayName fromValue(String v) {
        for (EoLCDAObservationTypeDisplayName c: EoLCDAObservationTypeDisplayName.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
