//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.30 at 12:27:07 PM BST 
//


package uk.nhs.ctp.service.report.org.hl7.v3;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EoLCDAObservationType_code.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="EoLCDAObservationType_code">
 *   &lt;restriction base="{urn:hl7-org:v3}cs">
 *     &lt;enumeration value="EOLCP"/>
 *     &lt;enumeration value="EOLTLU"/>
 *     &lt;enumeration value="EOLTST"/>
 *     &lt;enumeration value="EOLPRD"/>
 *     &lt;enumeration value="EOLPR"/>
 *     &lt;enumeration value="EOLADP"/>
 *     &lt;enumeration value="EOLADL"/>
 *     &lt;enumeration value="EOLADS"/>
 *     &lt;enumeration value="EOLBLC"/>
 *     &lt;enumeration value="EOLDCR"/>
 *     &lt;enumeration value="EOLDDL"/>
 *     &lt;enumeration value="EOLAOP"/>
 *     &lt;enumeration value="EOLLPA"/>
 *     &lt;enumeration value="EOLDRD"/>
 *     &lt;enumeration value="EOLRST"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "EoLCDAObservationType_code")
@XmlEnum
public enum EoLCDAObservationTypeCode {

    EOLCP,
    EOLTLU,
    EOLTST,
    EOLPRD,
    EOLPR,
    EOLADP,
    EOLADL,
    EOLADS,
    EOLBLC,
    EOLDCR,
    EOLDDL,
    EOLAOP,
    EOLLPA,
    EOLDRD,
    EOLRST;

    public String value() {
        return name();
    }

    public static EoLCDAObservationTypeCode fromValue(String v) {
        return valueOf(v);
    }

}
