//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.15 at 03:22:47 PM GMT 
//


package uk.nhs.ctp.service.report.org.hl7.v3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for II.NPfIT.oid.mandatory complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="II.NPfIT.oid.mandatory">
 *   &lt;complexContent>
 *     &lt;restriction base="{urn:hl7-org:v3}II.NPfIT.oid.required">
 *       &lt;attribute name="root" use="required" type="{urn:hl7-org:v3}II.NPfIT.root.oid" />
 *       &lt;attribute name="extension" use="required" type="{urn:hl7-org:v3}st" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "II.NPfIT.oid.mandatory")
public class IINPfITOidMandatory
    extends IINPfITOidRequired
{


}
