//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.15 at 03:22:47 PM GMT 
//


package uk.nhs.ctp.service.report.org.hl7.v3;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NHS111RepeatCallerServiceResponseType_displayName.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="NHS111RepeatCallerServiceResponseType_displayName">
 *   &lt;restriction base="{urn:hl7-org:v3}st">
 *     &lt;enumeration value="Repeat Caller"/>
 *     &lt;enumeration value="Not Repeat Caller"/>
 *     &lt;enumeration value="Potential Repeat Caller"/>
 *     &lt;enumeration value="Insufficient Information for Query"/>
 *     &lt;enumeration value="Repeat Caller Service Error"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "NHS111RepeatCallerServiceResponseType_displayName")
@XmlEnum
public enum NHS111RepeatCallerServiceResponseTypeDisplayName {

    @XmlEnumValue("Repeat Caller")
    REPEAT_CALLER("Repeat Caller"),
    @XmlEnumValue("Not Repeat Caller")
    NOT_REPEAT_CALLER("Not Repeat Caller"),
    @XmlEnumValue("Potential Repeat Caller")
    POTENTIAL_REPEAT_CALLER("Potential Repeat Caller"),
    @XmlEnumValue("Insufficient Information for Query")
    INSUFFICIENT_INFORMATION_FOR_QUERY("Insufficient Information for Query"),
    @XmlEnumValue("Repeat Caller Service Error")
    REPEAT_CALLER_SERVICE_ERROR("Repeat Caller Service Error");
    private final String value;

    NHS111RepeatCallerServiceResponseTypeDisplayName(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static NHS111RepeatCallerServiceResponseTypeDisplayName fromValue(String v) {
        for (NHS111RepeatCallerServiceResponseTypeDisplayName c: NHS111RepeatCallerServiceResponseTypeDisplayName.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
