//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.15 at 03:22:47 PM GMT 
//


package uk.nhs.ctp.service.report.org.hl7.v3;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NHS111MessageType_displayName.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="NHS111MessageType_displayName">
 *   &lt;restriction base="{urn:hl7-org:v3}st">
 *     &lt;enumeration value="NHS111 Repeat Caller Database Request"/>
 *     &lt;enumeration value="NHS111 Repeat Caller Database Response"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "NHS111MessageType_displayName")
@XmlEnum
public enum NHS111MessageTypeDisplayName {

    @XmlEnumValue("NHS111 Repeat Caller Database Request")
    NHS_111_REPEAT_CALLER_DATABASE_REQUEST("NHS111 Repeat Caller Database Request"),
    @XmlEnumValue("NHS111 Repeat Caller Database Response")
    NHS_111_REPEAT_CALLER_DATABASE_RESPONSE("NHS111 Repeat Caller Database Response");
    private final String value;

    NHS111MessageTypeDisplayName(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static NHS111MessageTypeDisplayName fromValue(String v) {
        for (NHS111MessageTypeDisplayName c: NHS111MessageTypeDisplayName.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
