//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.30 at 12:27:07 PM BST 
//


package uk.nhs.ctp.service.report.org.hl7.v3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PN.NHS.PersonNameType6 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PN.NHS.PersonNameType6">
 *   &lt;complexContent>
 *     &lt;restriction base="{urn:hl7-org:v3}PN.NHS.Internal">
 *       &lt;sequence>
 *         &lt;element name="given" type="{urn:hl7-org:v3}en.given"/>
 *         &lt;element name="family" type="{urn:hl7-org:v3}en.family"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PN.NHS.PersonNameType6")
public class PNNHSPersonNameType6
    extends PNNHSInternal
{


}
