//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.30 at 12:27:07 PM BST 
//


package uk.nhs.ctp.service.report.org.hl7.v3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for POCD_MT030001UK01.ClinicalDocument.typeId complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="POCD_MT030001UK01.ClinicalDocument.typeId">
 *   &lt;complexContent>
 *     &lt;restriction base="{urn:hl7-org:v3}II">
 *       &lt;attribute name="root" use="required" type="{urn:hl7-org:v3}uid" fixed="2.16.840.1.113883.1.3" />
 *       &lt;attribute name="extension" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{urn:hl7-org:v3}st">
 *             &lt;enumeration value="POCD_HD000040"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "POCD_MT030001UK01.ClinicalDocument.typeId")
public class POCDMT030001UK01ClinicalDocumentTypeId
    extends II
{


}
