//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.22 at 09:15:14 AM GMT 
//


package uk.nhs.ctp.service.report.org.hl7.v3;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import uk.nhs.ctp.service.report.npfit.hl7.localisation.TemplateContent;


/**
 * <p>Java class for REPC_MT200001GB02.Informant complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="REPC_MT200001GB02.Informant">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{urn:hl7-org:v3}InfrastructureRootElements"/>
 *         &lt;element ref="{NPFIT:HL7:Localisation}contentId"/>
 *         &lt;choice>
 *           &lt;group ref="{urn:hl7-org:v3}NPFIT-000085_Role"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{urn:hl7-org:v3}InfrastructureRootAttributes"/>
 *       &lt;attribute name="typeCode" use="required" type="{urn:hl7-org:v3}cs" fixed="INF" />
 *       &lt;attribute name="contextControlCode" use="required" type="{urn:hl7-org:v3}ContextControl" fixed="OP" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "REPC_MT200001GB02.Informant", propOrder = {
    "contentId",
    "cocdtp145007UK03RelatedEntity",
    "cocdtp145210GB01AssignedEntity",
    "cocdtp145007UK05RelatedEntity"
})
public class REPCMT200001GB02Informant {

    @XmlElement(namespace = "NPFIT:HL7:Localisation", required = true)
    protected TemplateContent contentId;
    @XmlElement(name = "COCD_TP145007UK03.RelatedEntity")
    protected COCDTP145007UK03RelatedEntity cocdtp145007UK03RelatedEntity;
    @XmlElement(name = "COCD_TP145210GB01.AssignedEntity")
    protected COCDTP145210GB01AssignedEntity cocdtp145210GB01AssignedEntity;
    @XmlElement(name = "COCD_TP145007UK05.RelatedEntity")
    protected COCDTP145007UK05RelatedEntity cocdtp145007UK05RelatedEntity;
    @XmlAttribute(name = "typeCode", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String typeCode;
    @XmlAttribute(name = "contextControlCode", required = true)
    protected List<String> contextControlCode;
    @XmlAttribute(name = "nullFlavor")
    protected List<String> nullFlavor;
    @XmlAttribute(name = "updateMode")
    protected CsUpdateMode updateMode;

    /**
     * Gets the value of the contentId property.
     * 
     * @return
     *     possible object is
     *     {@link TemplateContent }
     *     
     */
    public TemplateContent getContentId() {
        return contentId;
    }

    /**
     * Sets the value of the contentId property.
     * 
     * @param value
     *     allowed object is
     *     {@link TemplateContent }
     *     
     */
    public void setContentId(TemplateContent value) {
        this.contentId = value;
    }

    /**
     * Gets the value of the cocdtp145007UK03RelatedEntity property.
     * 
     * @return
     *     possible object is
     *     {@link COCDTP145007UK03RelatedEntity }
     *     
     */
    public COCDTP145007UK03RelatedEntity getCOCDTP145007UK03RelatedEntity() {
        return cocdtp145007UK03RelatedEntity;
    }

    /**
     * Sets the value of the cocdtp145007UK03RelatedEntity property.
     * 
     * @param value
     *     allowed object is
     *     {@link COCDTP145007UK03RelatedEntity }
     *     
     */
    public void setCOCDTP145007UK03RelatedEntity(COCDTP145007UK03RelatedEntity value) {
        this.cocdtp145007UK03RelatedEntity = value;
    }

    /**
     * Gets the value of the cocdtp145210GB01AssignedEntity property.
     * 
     * @return
     *     possible object is
     *     {@link COCDTP145210GB01AssignedEntity }
     *     
     */
    public COCDTP145210GB01AssignedEntity getCOCDTP145210GB01AssignedEntity() {
        return cocdtp145210GB01AssignedEntity;
    }

    /**
     * Sets the value of the cocdtp145210GB01AssignedEntity property.
     * 
     * @param value
     *     allowed object is
     *     {@link COCDTP145210GB01AssignedEntity }
     *     
     */
    public void setCOCDTP145210GB01AssignedEntity(COCDTP145210GB01AssignedEntity value) {
        this.cocdtp145210GB01AssignedEntity = value;
    }

    /**
     * Gets the value of the cocdtp145007UK05RelatedEntity property.
     * 
     * @return
     *     possible object is
     *     {@link COCDTP145007UK05RelatedEntity }
     *     
     */
    public COCDTP145007UK05RelatedEntity getCOCDTP145007UK05RelatedEntity() {
        return cocdtp145007UK05RelatedEntity;
    }

    /**
     * Sets the value of the cocdtp145007UK05RelatedEntity property.
     * 
     * @param value
     *     allowed object is
     *     {@link COCDTP145007UK05RelatedEntity }
     *     
     */
    public void setCOCDTP145007UK05RelatedEntity(COCDTP145007UK05RelatedEntity value) {
        this.cocdtp145007UK05RelatedEntity = value;
    }

    /**
     * Gets the value of the typeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTypeCode() {
        if (typeCode == null) {
            return "INF";
        } else {
            return typeCode;
        }
    }

    /**
     * Sets the value of the typeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypeCode(String value) {
        this.typeCode = value;
    }

    /**
     * Gets the value of the contextControlCode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the contextControlCode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContextControlCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getContextControlCode() {
        if (contextControlCode == null) {
            contextControlCode = new ArrayList<String>();
        }
        return this.contextControlCode;
    }

    /**
     * Gets the value of the nullFlavor property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the nullFlavor property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNullFlavor().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getNullFlavor() {
        if (nullFlavor == null) {
            nullFlavor = new ArrayList<String>();
        }
        return this.nullFlavor;
    }

    /**
     * Gets the value of the updateMode property.
     * 
     * @return
     *     possible object is
     *     {@link CsUpdateMode }
     *     
     */
    public CsUpdateMode getUpdateMode() {
        return updateMode;
    }

    /**
     * Sets the value of the updateMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link CsUpdateMode }
     *     
     */
    public void setUpdateMode(CsUpdateMode value) {
        this.updateMode = value;
    }

}
