//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.15 at 03:22:47 PM GMT 
//


package uk.nhs.ctp.service.report.org.hl7.v3;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SealingActType_displayName.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="SealingActType_displayName">
 *   &lt;restriction base="{urn:hl7-org:v3}st">
 *     &lt;enumeration value="Request to seal"/>
 *     &lt;enumeration value="Sealing event"/>
 *     &lt;enumeration value="Unsealing event"/>
 *     &lt;enumeration value="Refusal to seal"/>
 *     &lt;enumeration value="Refusal reason"/>
 *     &lt;enumeration value="Request to unseal"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "SealingActType_displayName")
@XmlEnum
public enum SealingActTypeDisplayName {

    @XmlEnumValue("Request to seal")
    REQUEST_TO_SEAL("Request to seal"),
    @XmlEnumValue("Sealing event")
    SEALING_EVENT("Sealing event"),
    @XmlEnumValue("Unsealing event")
    UNSEALING_EVENT("Unsealing event"),
    @XmlEnumValue("Refusal to seal")
    REFUSAL_TO_SEAL("Refusal to seal"),
    @XmlEnumValue("Refusal reason")
    REFUSAL_REASON("Refusal reason"),
    @XmlEnumValue("Request to unseal")
    REQUEST_TO_UNSEAL("Request to unseal");
    private final String value;

    SealingActTypeDisplayName(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SealingActTypeDisplayName fromValue(String v) {
        for (SealingActTypeDisplayName c: SealingActTypeDisplayName.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
