//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.30 at 12:27:07 PM BST 
//


package uk.nhs.ctp.service.report.org.hl7.v3;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ServiceEventType_displayName.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ServiceEventType_displayName">
 *   &lt;restriction base="{urn:hl7-org:v3}st">
 *     &lt;enumeration value="Personal Health Monitoring Event"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ServiceEventType_displayName")
@XmlEnum
public enum ServiceEventTypeDisplayName {

    @XmlEnumValue("Personal Health Monitoring Event")
    PERSONAL_HEALTH_MONITORING_EVENT("Personal Health Monitoring Event");
    private final String value;

    ServiceEventTypeDisplayName(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ServiceEventTypeDisplayName fromValue(String v) {
        for (ServiceEventTypeDisplayName c: ServiceEventTypeDisplayName.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
