//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.15 at 03:22:47 PM GMT 
//


package uk.nhs.ctp.service.report.xhtml.npfit.presentationtext;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for bodyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="bodyType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element ref="{xhtml:NPfIT:PresentationText}h2"/>
 *         &lt;element ref="{xhtml:NPfIT:PresentationText}h3"/>
 *         &lt;element ref="{xhtml:NPfIT:PresentationText}h4"/>
 *         &lt;element ref="{xhtml:NPfIT:PresentationText}h5"/>
 *         &lt;element ref="{xhtml:NPfIT:PresentationText}h6"/>
 *         &lt;element ref="{xhtml:NPfIT:PresentationText}p"/>
 *         &lt;element ref="{xhtml:NPfIT:PresentationText}ol"/>
 *         &lt;element ref="{xhtml:NPfIT:PresentationText}ul"/>
 *         &lt;element ref="{xhtml:NPfIT:PresentationText}table"/>
 *         &lt;element ref="{xhtml:NPfIT:PresentationText}a"/>
 *         &lt;element ref="{xhtml:NPfIT:PresentationText}pre"/>
 *         &lt;element name="br" type="{xhtml:NPfIT:PresentationText}brType"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "bodyType", propOrder = {
    "h2OrH3OrH4"
})
public class BodyType {

    @XmlElements({
        @XmlElement(name = "h2", type = H2 .class),
        @XmlElement(name = "h3", type = H3 .class),
        @XmlElement(name = "h4", type = H4 .class),
        @XmlElement(name = "h5", type = H5 .class),
        @XmlElement(name = "h6", type = H6 .class),
        @XmlElement(name = "p", type = P.class),
        @XmlElement(name = "ol", type = Ol.class),
        @XmlElement(name = "ul", type = Ul.class),
        @XmlElement(name = "table", type = Table.class),
        @XmlElement(name = "a", type = A.class),
        @XmlElement(name = "pre", type = Pre.class),
        @XmlElement(name = "br", type = BrType.class)
    })
    protected List<Object> h2OrH3OrH4;

    /**
     * Gets the value of the h2OrH3OrH4 property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the h2OrH3OrH4 property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getH2OrH3OrH4().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link H2 }
     * {@link H3 }
     * {@link H4 }
     * {@link H5 }
     * {@link H6 }
     * {@link P }
     * {@link Ol }
     * {@link Ul }
     * {@link Table }
     * {@link A }
     * {@link Pre }
     * {@link BrType }
     * 
     * 
     */
    public List<Object> getH2OrH3OrH4() {
        if (h2OrH3OrH4 == null) {
            h2OrH3OrH4 = new ArrayList<Object>();
        }
        return this.h2OrH3OrH4;
    }

}
