//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.15 at 03:22:47 PM GMT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "xhtml:NPfIT:PresentationText", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package uk.nhs.ctp.service.report.xhtml.npfit.presentationtext;
