# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Maven
      env:
        SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/cdss_decoupling?useSSL=false
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD: root
      run: |
        sudo systemctl start mysql
        mysql -uroot -proot < $GITHUB_WORKSPACE/src/main/resources/sql/create_database.sql
        mvn -B package --file pom.xml

  publish-app:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Push EMS Backend to GitHub Packages
      uses: docker/build-push-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        repository: uecit/cdss-ems/latest
        tag_with_ref: true

  publish-ui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Push EMS UI to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          path: EMS-UI
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: uecit/cdss-ems/ui
          tag_with_ref: true
